export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_STARS = 'RECEIVE_STARS';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const INVALIDATE_HATEBU = 'INVALIDATE_HATEBU';
